version: '3.7'

services:
    naming-server:
        image: rakeshmitt/mmv2-naming-server:0.0.1-SNAPSHOT
        ports: 
          - "8761:8761"
        networks:
          - currency-network
        
    currency-exchange:
        image: rakeshmitt/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8000:8000"
        networks:
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
          SPRING.ZIPKIN.SENDER.TYPE: rabbit
          SPRING.RABBITMQ.HOST: rabbitmq
          RABBIT_URI: amqp://guest:guest@rabbitmq:5672

    currency-conversion:
        image: rakeshmitt/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8100:8100"
        networks:
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
          SPRING.ZIPKIN.SENDER.TYPE: rabbit
          SPRING.RABBITMQ.HOST: rabbitmq
          RABBIT_URI: amqp://guest:guest@rabbitmq:5672

    api-gateway:
        image: rakeshmitt/mmv2-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8765:8765"
        networks:
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          #EUREKA.CLIENT.FETCHREGISTRY: "true"
          SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
          SPRING.ZIPKIN.SENDER.TYPE: rabbit
          SPRING.RABBITMQ.HOST: rabbitmq
          RABBIT_URI: amqp://guest:guest@rabbitmq:5672
          
    zipkin-server:
        image: openzipkin/zipkin
        mem_limit: 300m
        restart: always
        ports:
          - "9411:9411"
        networks:
          - currency-network
        environment:
          RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        depends_on:
          - rabbitmq

    rabbitmq:
        image: rabbitmq:3.9.0-management
        mem_limit: 300m
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - currency-network
          
networks:
    currency-network: